### ISSUE TITLE
Fail on connection

### ISSUE THREAD

**Issue by krikunts** [02strich/python-pandora#5]
I get auth=false with your previous partner auth and folowing error with new one:

Traceback (most recent call last):
  File "pandora_test.py", line 10, in <module>
    pandora = Pandora()
  File "C:\play4last\pandora\pandora.py", line 21, in **init**
    self.connection = connection_class()
  File "C:\play4last\pandora\connection.py", line 46, in **init**
    raise Exception("Establishing connection to Pandora failed")
Exception: Establishing connection to Pandora failed

Do you encounter the same error? Maybe it's Pandora API changes?

**Comment by 02strich** [comment]
Hi,

sorry for the late response. It works for me without an issue. Are you sure, you correctly configured the way to get to the Pandora servers, i.e. a proxy or something? Please also note, that not only the partner username changed, but also the server endpoint, so maybe something needs to be adapted due to this?

Thanks

**Comment by 02strich** [comment]
No response means issue is solved, therefore closing this. Please re-open of neccessary
